config/routes.rb
Rails.application.routes.draw do
  get 'jobs/show'

  get 'jobs/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'platforms#index'
  resources :platforms do
    resources :apps do
      resources :jobs do
        resources :commands do
        end
      end
      member do
        post :deploy_process
        post :reseed
        post :create_convox_application
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :platform
  has_many :jobs

  validates :branch, uniqueness: true,  presence: true, length: {minimum: 4}
  validates :name, uniqueness: true, length: {minimum: 4, maximum: 30}, allow_blank: true
  before_validation:set_name

  private
  def set_name
    self.name = branch.scan(/\w|-/).join[0,30]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/command.rb
class Command < ApplicationRecord
  belongs_to :job
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :commands
  belongs_to :app
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :apps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_platform
  before_action :set_app, only: [:show, :edit, :update, :destroy, :deploy_process, :reseed, :create_convox_application ]

  # GET /apps
  # GET /apps.json
  def index
    @apps = @platform.apps = @platform.apps
  end

  # GET /apps/new
  def new
    @app = @platform.apps.new
  end

  # GET /apps/1/edit
  def edit
  end

  def show
    @jobs = @app.jobs
  end

  # POST /platforms/1/deploy_process
  def deploy_process
    flash[:notice] = "Updating and Promoting application: #{@app.name}"
    DeployProcessWorker.perform_async(@app.id)
    redirect_to platform_app_path(@platform, @app)
  end

  def reseed
    flash[:notice] = "Reseeding Application: #{@app.name}"
    ReseedDatabaseWorker.perform_async(@app.id)
    redirect_to platform_app_path(@platform, @app)
  end

  def create_convox_application
    flash[:notice] = "Creating Application: #{@app.name}"
    CreateConvoxApplicationWorker.perform_async(@app.id)
    redirect_to platform_app_path(@platform, @app)
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = @platform.apps.new(app_params)

    respond_to do |format|
      if @app.save
        STDOUT << "SAVED!"
        format.html { redirect_to platform_apps_path(@platform), notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        STDOUT << " Failed to SAVED!"
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to platform_apps_path(@platform), notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to platform_apps_path(@platform), notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = @platform.apps.find(params[:id])
    end

    def set_platform
      @platform = Platform.find(params[:platform_id]) # TODO: secruity
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:branch, :url, :release)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_app
  def show
    @job = @app.jobs.find(params[:id])
  end

  private
  def set_app
    @platform = Platform.find(params[:platform_id])
    @app = @platform.apps.find(params[:app_id])

  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(platform_params)

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1
  # PATCH/PUT /platforms/1.json
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { render :show, status: :ok, location: @platform }
      else
        format.html { render :edit }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url, notice: 'Platform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:name, :login, :auth_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/apps/_form.html.erb
<%= form_for([@platform, app]) do |f| %>
  <% if app.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

        <ul>
          <% app.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :branch %>
    <%= f.text_field :branch, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pr, 'Pull Request #' %>
    <%= f.text_field :pr, class: 'form-control' %>
  </div>

  <% if app.id.present? %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', disabled: true %>
    </div>

    <div class="form-group">
      <%= f.label :release %>
      <%= f.text_field :release, class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%=image_tag 'hound', width:'100%', style: 'position:absolute; right: 0; opacity: 0.2; z-index: -1' -%>

      <h3>Links</h3>
      <ul class="nav nav-sidebar ">
        <li><%= link_to 'Back', platform_app_path(@platform, @app) %></li>
      </ul>
    </div>
    <div class="col-sm-5 col-sm-offset-3 col-md-5 col-md-offset-2 main">


    <h1>Edit App</h1>
    <p>
      Branch name must match github exactly
      <br/>
      App name is auto genereated from branch
    </p>

    <%= render 'form', app: @app %>

    </div>
  </div>
</div>

app/views/apps/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%=image_tag 'hound', width:'100%', style: 'position:absolute; right: 0; opacity: 0.2; z-index: -1' -%>
      <a href="/"><h3>Convox Racks</h3></a>

      <ul class="nav nav-sidebar hound-bg">

        <% Platform.all.each do |plat| %>
            <li class="<%="active" if @platform.id == plat.id -%>" >
              <a href="<%=platform_apps_path(plat)%>" href=><%=plat.name %><span class="sr-only">(current)</span></a>
            </li>
        <% end %>
      </ul>
      <br/>
      <br/>

    </div>

    <div class="col-sm-7 col-sm-offset-3 col-md-8 col-md-offset-2 main">
      <h2 class="sub-header">Active Branches: <%=@platform.name %></h2>

      <p id="notice"><%= notice %></p>

      <br/>
      <%= button_to 'New Convox App', new_platform_app_path(@platform), class: 'btn-primary', method: :get %>
      <br/>
      <br/>

      <div class="row placeholders">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center">Convox App </th>
                <th class="text-center">Branch / PR</th>
                <th class="text-center">Visit</th>
                <th class="text-center">Jobs</th>
              </tr>
            </thead>

            <tbody>
            <% @apps.each do |app| %>
              <tr>
                <td><%= link_to app.name, platform_app_path(@platform, app), style: 'color: #3333ff' %></td>
                <td><%= app.branch%>&nbsp;/&nbsp;<%= app.pr || 'No PR' %></td>
                <td><%= link_to truncate(app.url), app.url, target: '_blank', style: 'color: #3333ff' %></td>
                <td><%= "Jobs (#{app.jobs.count})" %></td>
              </tr>
            <% end %>
            </tbody>
            </table>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/apps/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%=image_tag 'hound', width:'100%', style: 'position:absolute; right: 0' -%>
      </div>
    <div class="col-sm-5 col-sm-offset-3 col-md-5 col-md-offset-2 main">

      <h1 class="page-header">New Convox Application</h1>

      <%= render 'form', app: @app %>
      <%= link_to 'Back', platform_apps_path(@platform) %>
    </div>
  </div>
</div>

app/views/apps/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%=image_tag 'hound', width:'100%', style: 'position:absolute; right: 0; opacity: 0.2; z-index: -1' -%>

      <h3>Links</h3>
      <ul class="nav nav-sidebar ">
        <li><%= link_to 'Back', platform_apps_path(@platform) %></li>
        <li><%= link_to "Edit", edit_platform_app_path(@platform, @app), style: 'color: #3333ff' %></li>
      </ul>

      <br/>
      <br/>
      <h3>Actions</h3>
      <br/>
      <div class="btn-group-vertical">
        <% if @app.created %>
          <%= button_to 'Update from Github', deploy_process_platform_app_path(@platform, @app), class:'btn-larger-size btn btn btn-success', data: { confirm: "This will update to latest commit on branch #{@app.branch}" } %>
          <%= button_to 'Reseed DB', reseed_platform_app_path(@platform, @app), class:'btn-larger-size btn btn btn-warning', data: { confirm: 'This will delete the database and reseed. Are you sure?' } %>
        <% else %>
          <%= button_to 'Create Convox Application', create_convox_application_platform_app_path(@platform, @app),  class: 'btn-larger-size btn btn-warning btn', data: { confirm: 'This will Create the App on convox and deploy. Are you sure?' } %>
        <% end %>
        <%= button_to 'Destroy', '#', data: { confirm: 'Nope!' }, class: 'btn-larger-size btn btn btn-danger' %>
      </div>


      <br/>

    </div>

    <div class="col-sm-5 col-sm-offset-3 col-md-5 col-md-offset-2 main">
      <h2 class="sub-header"><%=@app.name %></h2>

      <p id="notice"><%= notice %></p>
      <p>
        <strong>Name:</strong>
        <%= @app.name %>
      </p>

      <p>
        <strong>Platform:</strong>
        <%= @app.platform.name %>
      </p>

      <p>
        <strong>Created:</strong>
        <%= !!@app.created %>
      </p>

      <p>
        <strong>Status:</strong>
        <%= @app.status %>
      </p>

      <p>
        <strong>Url:</strong>
        <%= @app.url %>
      </p>

      <h3>Jobs</h3>
      <div class="row placeholders">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th class="text-center"></th>
              <th class="text-center">Job Type</th>
              <th class="text-center">Status</th>
              <th class="text-center">Complete</th>
              <th class="text-center">Started At</th>
              <th class="text-center">Updated At</th>
            </tr>
            </thead>

            <tbody>
            <% @app.jobs.order('id desc').each do |job| %>
                <tr>
                  <td><%=link_to 'view',  platform_app_job_path(@platform, @app, job), class: 'btn btn-info btn-xs', method: :get -%></td>
                  <td><%=job.job_type -%></td>
                  <td><%=job.status-%></td>
                  <td><%=job.complete-%></td>
                  <td><%=job.created_at.to_s(:db)-%></td>
                  <td><%=job.updated_at.to_s(:dbk) -%></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>

app/views/jobs/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%=image_tag 'hound', width:'100%', style: 'position:absolute; right: 0; opacity: 0.2; z-index: -1' -%>

      <h3>Links</h3>
      <ul class="nav nav-sidebar ">
        <li> <a href="<%= platform_app_path(@platform, @app) %>">Back</a> </li>
      </ul>
    </div>

  </div>
  <div class=" col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h2 class="sub-header">Job: <%="#{@job.id} - #{@job.job_type}" %></h2>
    <br/>
    <br/>
    <b>Run at</b> <%=@job.created_at -%>
    <br/>
    <b>Status</b> <%=@job.status -%>
    <br/>
    <b>Progress</b> <%=number_with_precision(@job.commands.count*100 / @job.steps.to_f , :precision => 0) -%> %
    <br/>
    <hr/>

    <% @job.commands.order('id').each do |cli| %>
        <div class="row">
          <div class="col-sm-2 col-md-2 ">
              <b>Ran: </b><%=cli.created_at.to_s(:short)-%>
            <br/>
              <% if cli.status_code.nil? %>
                  <b>Time: </b><%=distance_of_time_in_words(DateTime.now.to_i - cli.created_at.to_i) %>
              <% else %>
                  <b>Time: </b><%=distance_of_time_in_words(cli.updated_at.to_i - cli.created_at.to_i) %>
              <% end %>
            <br/>
              <b>Step: </b><%=cli.step-%></li>
            <br/>
          </div>

          <div class="col-sm-10 col-md-10 main">
            <% if cli.status_code.nil? %>
                <div class="alert alert-info" role="alert">
            <% else %>

              <div class="alert <%= cli.status_code == 0 ? 'alert-success' : 'alert-danger' %>" role="alert">
            <% end %>
              <b><%= cli.cli %></b>
            </div>
            <pre style="max-height: 400px; background-color:#333;color:#eee"><%=cli.output %></pre>
          </div>
        </div>
        <hr/>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConvoxHooks</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="//getbootstrap.com/examples/dashboard/dashboard.css" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Argos the Loyal</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <!--<li><a href="#">Dashboard</a></li>-->
            <!--<li><a href="#">Settings</a></li>-->
            <!--<li><a href="#">Profile</a></li>-->
            <!--<li><a href="#">Help</a></li>-->
          </ul>
          <form class="navbar-form navbar-right">
            <!--<input type="text" class="form-control" placeholder="Search...">-->
          </form>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/platforms/_form.html.erb
<%= form_for(platform) do |f| %>
  <% if platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% platform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :auth_code %>
    <%= f.text_field :auth_code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%=image_tag 'hound', width:'100%', style: 'position:absolute; right: 0' -%>
    </div>

    <div class=" col-sm-7 col-sm-offset-3 col-md-8 col-md-offset-2 main">
      <h2 class="sub-header">Convox Racks: </h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Login</th>
            <th>Auth code</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @platforms.each do |platform| %>
            <tr>
              <td><%= button_to "Manage Applications (#{platform.apps.count})", platform_apps_path(platform), method: :get, class: 'btn btn-xs btn-info' %></td>
              <td><%= platform.name %></td>
              <td><%= platform.login %></td>
              <td><%= "*"*10 %></td>
              <td><%= link_to 'Show', platform %></td>
              <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
              <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= button_to 'New Convox Rack', new_platform_path, class: 'btn btn-primary', data: {confirm: 'Do not connect to a production instance!'}, method: :get %>
    </div>
  </div>
</div>

app/views/platforms/new.html.erb
<h1>New Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @platform.name %>
</p>

<p>
  <strong>Login:</strong>
  <%= @platform.login %>
</p>

<p>
  <strong>Auth code:</strong>
  <%= @platform.auth_code %>
</p>

<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>